[package]
name = "cypress1/get-different-child"
version = "0.1.0"
description = "wasmer-tests/wasmer-edge-gatsby-sample website"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = "public"
